FROM php:7.4-fpm

# Add configuration files
COPY ./development/docker/workspace/ /

RUN curl -sL https://deb.nodesource.com/setup_12.x | bash - \
    && curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - \
    && echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list

# Installing the necessary components and PHP Extensions
RUN apt-get update \
    && apt-get install -y \
        nodejs \
        yarn \
        git \
        zip \
        unzip \
        nano \
        mc \
        libonig-dev \
        libzip-dev \
        libicu-dev \
        libxml2-dev \
        libpng-dev \
        libfreetype6-dev \
        libjpeg62-turbo-dev \
        libpng-dev \
        libpq-dev \
    --no-install-recommends && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install -j$(nproc) gd

RUN docker-php-ext-install -j$(nproc) bcmath iconv mbstring pdo pdo_pgsql zip json pcntl exif xml intl

# Install PECL extensions
RUN pecl install xdebug

# Environment settings
ENV PHP_ENABLE_XDEBUG=0 \
    TERM=linux \
    COMPOSER_ALLOW_SUPERUSER=1

# Add GITHUB_API_TOKEN support for composer
RUN chmod 700 \
        /usr/local/bin/docker-php-entrypoint \
        /usr/local/bin/composer

# Install composer
RUN curl -sS https://getcomposer.org/installer | php -- \
        --filename=composer.phar \
        --install-dir=/usr/local/bin \
    && composer clear-cache

WORKDIR /var/www/html/
